---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: swiggy
        image: yaswanth102002/git-docker-repo:latest
        ports:
        - containerPort: 6000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80.
    targetPort: 6000
  type: LoadBalancer
